services:
  jenkins:
    image: jenkins/jenkins:jdk21
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - jenkins_home:/var/jenkins_home

  reverse-proxy:
    build: ../michielidema-net-reverse-proxy/ 
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./certbot/www/:/var/www/certbot/:ro  
      - ./certbot/conf/archive/michielidema.net/:/etc/nginx/ssl/archive/michielidema.net/

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw    
          
volumes:
  jenkins_home:
    