services:
  jenkins:
    image: jenkins/jenkins:jdk21
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home

  reverse-proxy:
    build: ../michielidema-net-reverse-proxy/ 
    ports:
      - 443:443
      - 80:80
          

volumes:
  jenkins_home:
    